[pytest]
addopts = -q -s --basetemp=.pytest_local_tmp/tmp
cache_dir = .pytest_local_tmp/.pytest_cache
python_files = test_*.py
markers =
    integration: integration-level tests
    slow: long-running tests
